
// This snippet file was generated by processing the source file:
// ./messaging-next/index.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START messaging_get_messaging_object_modular]
import { getMessaging, getToken } from "firebase/messaging";

const messaging = getMessaging();
// [END messaging_get_messaging_object_modular]

// Add the public key generated from the console here.
messaging.getToken({vapidKey: "BD46HU7ebxQp5VLPdyZarE6N0XZJUACeb-arpCX8gdKHsugVuEjkBqof7UTZ4GUkymLVVExNs_tIMB4DStYCstc"});

getToken(messaging, { vapidKey: 'BD46HU7ebxQp5VLPdyZarE6N0XZJUACeb-arpCX8gdKHsugVuEjkBqof7UTZ4GUkymLVVExNs_tIMB4DStYCstc' })
.then((currentToken) => {
  if (currentToken) {
    // Send the token to your server and update the UI if necessary
    // ...
  } else {
    // Show permission request UI
    console.log('No registration token available. Request permission to generate one.');
    // ...
  }
}).catch((err) => {
  console.log('An error occurred while retrieving token. ', err);
  // ...
});